### ISSUE TITLE
Implement an Action endpoint route for your service

### ISSUE THREAD

**Issue by omb244** [CSCI-GA-2820-FA22-001/customers#40] opened 2022-11-01 21:03 UTC
**As a** service provider
 **I need** 
 **So that**
   
 ### Details and Assumptions
 * 
   
 ### Acceptance Criteria  
   
 ```gherkin

 ```

**Comment by kovidiament** [comment] 2022-11-11 00:42
duplicate of "set active flag"

**Closed** 2022-11-11 00:42 UTC
Labels: enhancement
